# My Makefile

check_string_rotation: check_string_rotation.c
	@gcc -g -Wall -Werror check_string_rotation.c -o check_string_rotation

all: check_string_rotation

clean: 
	@rm -f *.o
	@rm -f check_string_rotation

